project_name: praca-inz


task_api_base_url: http://praca-inz-cbd8a0-alb-761282482.eu-north-1.elb.amazonaws.com
result_service_base_url: http://praca-inz-cbd8a0-alb-761282482.eu-north-1.elb.amazonaws.com
default_headers:
  Content-Type: "application/json"

request_timeout_sec: 30
verify_tls: false
